#' Generate Summary
#'
#' This function generates the summary page of a \code{PCMH} QA error report.
#'
#' @param .detail A \code{dataframe} generated by \code{\link[pcmh]{generate_detail}}.
#' @param .prvdr_num A 9 digit \code{intiger}.
#'
#' @return Returns an nx2 \code{dataframe} for n \code{.prvdr_num}.
#' @export
#'
#' @examples
#' \dontrun{
#' generate_summary(.detail, .prvdr_num)
#' }
generate_summary <- function(.detail, .prvdr_num) {
  # Subset detail based on .prvdr_num
  detail <-
    .detail[which(.detail$prvdr_num == .prvdr_num), ]


  # Initialize output
  out <-
    detail["prvdr_num"] |>
    unique()

  # Number of Matches
  match_no <-
    detail[which(detail$mismatch_type == "Match"), ] |>
    nrow()

  # Number of Mismatches
  mismatch_no <-
    detail[which(detail$mismatch_type == "Mismatch"), ] |>
    nrow()

  # Number of Missing
  missing_no <-
    detail[which(detail$mismatch_type == "Missing"), ] |>
    nrow()

  # Summarize Mismatch Type for each Provider
  if (match_no == nrow(detail)) {
    out["mismatch_type"] <-
      "Match"
  } else if (mismatch_no > 0 &
             missing_no > 0) {
    out["mismatch_type"] <-
      "Missing/Mismatch"
  } else if (mismatch_no == 0 &
             missing_no > 0) {
    out["mismatch_type"] <-
      "Missing"
  } else if (mismatch_no > 0 &
             missing_no == 0) {
    out["mismatch_type"] <-
      "Mismatch"
  } else {
    out["mismatch_type"] <-
      "Other"
  }


  # Return output
  return(out)
}
