#' Generate Summary
#'
#' This function generates the summary page of a \code{PCMH} QA error report.
#'
#' @param .detail A \code{dataframe} generated by \code{\link[pcmh]{generate_detail}}.
#' @param .prvdr_num A 9 digit \code{intiger}.
#'
#' @return Returns an nx2 \code{dataframe} for n \code{.prvdr_num}.
#' @export
#'
#' @examples
#' \dontrun{
#' generate_summary(.detail, .prvdr_num)
#' }
generate_summary <- function(.detail, .prvdr_num) {
  # Subset detail based on .prvdr_num
  detail <-
    .detail[which(.detail$prvdr_num == .prvdr_num), ]

  # Initialize output
  out <-
    detail[1, "prvdr_num"]

  # Summarize Mismatch Type for each Provider
  if("Missing" %in% .detail[which(.detail$prvdr_num == .prvdr_num),
                            "mismatch_type"] &
     "Mismatch" %in% .detail[which(.detail$prvdr_num == .prvdr_num),
                             "mismatch_type"]) {
    out["type"] <-
      "Missing/Mismatch"
  } else if ("Missing" %in% .detail[which(.detail$prvdr_num == .prvdr_num),
                                    "mismatch_type"]) {
    out["type"] <-
      "Missing"
  } else if ("Mismatch" %in% .detail[which(.detail$prvdr_num == .prvdr_num),
                                     "mismatch_type"]) {
    out["type"] <-
      "Mismatch"
  } else {
    out["type"] <-
      # .detail["mismatch_type"]
      "Something unexpected"
  }

  # Give columns human readable names
  names(out) <-
    c("Provider Number",
      "Mismatch Type")

  # Return output
  return(out)
}
